[atoms.CH3_alkane]
name = "CH3_alkane"
mass = 15.035
epsilon = 0.2707
sigma = 3.6034
m = 14.0
cut = 14.0
charge = 0.0
style = "hybrid Mie/cut coul/long"

[atoms.CH3_MSH]
name = "CH3_MSH"
mass = 14.027
epsilon = 0.1451
sigma = 3.8257
m = 14.0
cut = 14.0
charge = 0.211
style = "hybrid Mie/cut coul/long"

[atoms.CH2_alkane]
name = "CH2_alkane"
mass = 14.027
epsilon = 0.1051
sigma = 4.04
m = 14.0
cut = 14.0
charge = 0.0
style = "hybrid Mie/cut coul/long"

[atoms.CH2_EOH]
name = "CH2_EOH"
mass = 14.027
epsilon = 0.1515
sigma = 3.899
m = 14.0
cut = 14.0
charge = 0.252
style = "hybrid Mie/cut coul/long"

[atoms.CH2_alcohol]
name = "CH2_alcohol"
mass = 14.027
epsilon = 0.1673
sigma = 3.842
m = 14.0
cut = 14.0
charge = 0.246
style = "hybrid Mie/cut coul/long"

[atoms.CH2_ESH]
name = "CH2_ESH"
mass = 14.027
epsilon = 0.1113
sigma = 4.0704
m = 14.0
cut = 14.0
charge = 0.211
style = "hybrid Mie/cut coul/long"

[atoms.CH2_thiol]
name = "CH2_thiol"
mass = 14.027
epsilon = 0.1255
sigma = 3.9178
m = 14.0
cut = 14.0
charge = 0.211
style = "hybrid Mie/cut coul/long"

[atoms.CH2_amine]
name = "CH2_amine"
mass = 14.027
epsilon = 0.1337
sigma = 3.9428
m = 14.0
cut = 14.0
charge = 0.168
style = "hybrid Mie/cut coul/long"

[atoms.OH_EOH]
name = "OH_EOH"
mass = 17.007
epsilon = 0.1515
sigma = 3.080
m = 12.0
cut = 14.0
charge = -0.667
style = "hybrid Mie/cut coul/long"

[atoms.OH_alcohol]
name = "OH_alcohol"
mass = 17.007
epsilon = 0.1673
sigma = 3.035
m = 12.0
cut = 14.0
charge = -0.65
style = "hybrid Mie/cut coul/long"

[atoms.O_SPCE]
name = "O_SPCE"
mass = 18.01528
epsilon = 0.1553
sigma = 3.16555789
m = 12.0
cut = 14.0
charge = -0.8476
style = "hybrid Mie/cut coul/long"

[atoms.SH_MSH]
name = "SH_MSH"
mass = 33.073
epsilon = 0.6054
sigma = 3.5059
m = 12.0
cut = 14.0
charge = -0.387
style = "hybrid Mie/cut coul/long"

[atoms.SH_ESH]
name = "SH_ESH"
mass = 33.073
epsilon = 0.3804
sigma = 3.7301
m = 12.0
cut = 14.0
charge = -0.387
style = "hybrid Mie/cut coul/long"

[atoms.SH_thiol]
name = "SH_thiol"
mass = 33.073
epsilon = 0.4291
sigma = 3.5902
m = 12.0
cut = 14.0
charge = -0.387
style = "hybrid Mie/cut coul/long"

[atoms.NH2_amine]
name = "NH2_amine"
mass = 16.023
epsilon = 0.2414
sigma = 3.295
m = 12.0
cut = 14.0
charge = -0.867
style = "hybrid Mie/cut coul/long"

[atoms.cH_alcohol]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.404
style = "hybrid Mie/cut coul/long"

[atoms.cH_EOH]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.415
style = "hybrid Mie/cut coul/long"

[atoms.cH_thiol]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.176
style = "hybrid Mie/cut coul/long"

[atoms.cH_MSH]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.176
style = "hybrid Mie/cut coul/long"

[atoms.cH_amine]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.3495
style = "hybrid Mie/cut coul/long"

[atoms.cH_SPCE]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.4238
style = "hybrid Mie/cut coul/long"

[bonds."[CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane",]
type = 1
p = [ 1.74, 200.0,]
style = "harmonic"

[bonds."[CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane",]
type = 1
p = [ 1.54, 200.0,]
style = "harmonic"

[bonds."[CH2_alcohol][CH2_alcohol]"]
list = [ "CH2_alcohol", "CH2_alcohol",]
type = 1
p = [ 1.514, 200.0,]
style = "harmonic"

[bonds."[CH2_EOH][CH2_EOH]"]
list = [ "CH2_EOH", "CH2_EOH",]
type = 1
p = [ 1.514, 200.0,]
style = "harmonic"

[bonds."[OH_EOH][cH_EOH]"]
list = [ "OH_EOH", "cH_EOH",]
type = 1
p = [ 0.97, 200.0,]
style = "harmonic"

[bonds."[CH2_EOH][OH_EOH]"]
list = [ "CH2_EOH", "OH_EOH",]
type = 1
p = [ 1.42, 200.0,]
style = "harmonic"

[bonds."[OH_alcohol][cH_alcohol]"]
list = [ "OH_alcohol", "cH_alcohol",]
type = 1
p = [ 0.97, 200.0,]
style = "harmonic"

[bonds."[CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alcohol", "OH_alcohol",]
type = 1
p = [ 1.42, 200.0,]
style = "harmonic"

[bonds."[CH2_alcohol][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alcohol",]
type = 1
p = [ 1.514, 200.0,]
style = "harmonic"

[bonds."[CH2_EOH][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_EOH",]
type = 1
p = [ 1.714, 200.0,]
style = "harmonic"


[bonds."[CH2_ESH][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_ESH",]
type = 1
p = [ 1.54, 200.0,]
style = "harmonic"

[bonds."[SH_ESH][cH_ESH]"]
list = [ "SH_ESH", "cH_ESH",]
type = 1
p = [ 1.34, 200.0,]
style = "harmonic"

[bonds."[CH2_ESH][SH_ESH]"]
list = [ "CH2_ESH", "SH_ESH",]
type = 1
p = [ 1.82, 200.0,]
style = "harmonic"

[bonds."[SH_MSH][cH_MSH]"]
list = [ "SH_MSH", "cH_MSH",]
type = 1
p = [ 1.34, 200.0,]
style = "harmonic"

[bonds."[CH3_MSH][SH_MSH]"]
list = [ "CH3_MSH", "SH_MSH",]
type = 1
p = [ 1.82, 200.0,]
style = "harmonic"

[bonds."[SH_thiol][cH_thiol]"]
list = [ "SH_thiol", "cH_thiol",]
type = 1
p = [ 1.34, 200.0,]
style = "harmonic"

[bonds."[CH2_thiol][SH_thiol]"]
list = [ "CH2_thiol", "SH_thiol",]
type = 1
p = [ 1.82, 200.0,]
style = "harmonic"

[bonds."[CH2_alkane][CH2_thiol]"]
list = [ "CH2_alkane", "CH2_thiol",]
type = 1
p = [ 1.54, 200.0,]
style = "harmonic"

[bonds."[CH2_amine][NH2_amine]"]
list = [ "NH2_amine", "CH2_amine",]
type = 1
p = [ 1.448, 200.0,]
style = "harmonic"

[bonds."[CH2_alkane][CH2_amine]"]
list = [ "CH2_amine", "CH2_alkane",]
type = 1
p = [ 1.54, 200.0,]
style = "harmonic"

[bonds."[CH2_amine][CH3_alkane]"]
list = [ "CH2_amine", "CH3_alkane",]
type = 1
p = [ 1.74, 200.0,]
style = "harmonic"

[bonds."[NH2_amine][cH_amine]"]
list = [ "NH2_amine", "cH_amine",]
type = 1
p = [ 1.01, 200.0,]
style = "harmonic"

[bonds."[O_SPCE][cH_SPCE]"]
list = [ "O_SPCE", "cH_SPCE",]
type = 1
p = [ 1.0, 200.0,]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_alkane",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_alcohol][OH_alcohol][cH_alcohol]"]
list = [ "CH2_alcohol", "OH_alcohol", "cH_alcohol",]
type = 2
p = [ 107.4, 45.6354,]
style = "harmonic"

[angles."[CH2_alkane][CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alkane", "CH2_alcohol", "OH_alcohol",]
type = 2
p = [ 113.5, 61.8104,]
style = "harmonic"

[angles."[CH2_alcohol][CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alcohol", "CH2_alcohol", "OH_alcohol",]
type = 2
p = [ 113.5, 61.8104,]
style = "harmonic"

[angles."[CH2_alcohol][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alcohol",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_alcohol][CH2_alkane][CH2_alcohol]"]
list = [ "CH2_alcohol", "CH2_alkane", "CH2_alcohol",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_EOH][OH_EOH][cH_EOH]"]
list = [ "CH2_EOH", "OH_EOH", "cH_EOH",]
type = 2
p = [ 107.4, 45.6354,]
style = "harmonic"

[angles."[CH3_alkane][CH2_EOH][OH_EOH]"]
list = [ "CH3_alkane", "CH2_EOH", "OH_EOH",]
type = 2
p = [ 113.5, 61.8104,]
style = "harmonic"


[angles."[CH2_thiol][SH_thiol][cH_thiol]"]
list = [ "CH2_thiol", "SH_thiol", "cH_thiol",]
type = 2
p = [ 96.0, 33.5911,]
style = "harmonic"

[angles."[CH2_alkane][CH2_thiol][SH_thiol]"]
list = [ "CH2_alkane", "CH2_thiol", "SH_thiol",]
type = 2
p = [ 114.0, 61.8104,]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH2_thiol]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_thiol",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_thiol][CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_thiol",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_ESH][SH_ESH][cH_ESH]"]
list = [ "CH2_ESH", "SH_ESH", "cH_ESH",]
type = 2
p = [ 96.0, 62.0586,]
style = "harmonic"

[angles."[CH3_alkane][CH2_ESH][SH_ESH]"]
list = [ "CH3_alkane", "CH2_ESH", "SH_ESH",]
type = 2
p = [ 114.0, 61.8104,]
style = "harmonic"

[angles."[CH3_MSH][SH_MSH][cH_MSH]"]
list = [ "CH3_MSH", "SH_MSH", "cH_MSH",]
type = 2
p = [ 96.0, 62.0586,]
style = "harmonic"

[angles."[CH2_amine][CH2_alkane][CH2_alkane]"]
list = [ "CH2_amine", "CH2_alkane", "CH2_alkane",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH2_amine]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_amine",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_amine][CH2_alkane][CH3_alkane]"]
list = [ "CH2_amine", "CH2_alkane", "CH3_alkane",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH3_alkane][CH2_amine][NH2_amine]"]
list = [ "CH3_alkane", "CH2_amine", "NH2_amine",]
type = 2
p = [ 109.5, 56.2003,]
style = "harmonic"

[angles."[CH2_alkane][CH2_amine][NH2_amine]"]
list = [ "CH2_alkane", "CH2_amine", "NH2_amine",]
type = 2
p = [ 109.5, 56.2003,]
style = "harmonic"

[angles."[CH2_amine][NH2_amine][cH_amine]"]
list = [ "CH2_amine", "NH2_amine", "cH_amine",]
type = 2
p = [ 112.9, 62.0586,]
style = "harmonic"

[angles."[cH_amine][NH2_amine][cH_amine]"]
list = [ "cH_amine", "NH2_amine", "cH_amine",]
type = 2
p = [ 106.4, 43.5999,]
style = "harmonic"

[angles."[cH_SPCE][O_SPCE][cH_SPCE]"]
list = [ "cH_SPCE", "O_SPCE", "cH_SPCE",]
type = 1
p = [ 109.47, 99.2937,]
style = "harmonic"

[torsions."[CH3_alkane][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_alkane", "CH3_alkane",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH3_alkane",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH2_alkane",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alcohol][OH_alcohol][cH_alcohol]"]
list = [ "CH2_alkane", "CH2_alcohol", "OH_alcohol", "cH_alcohol",]
type = 1
p = [ -0.7347, 0.3257, 0.1465, 1.2068, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alcohol][OH_alcohol][cH_alcohol]"]
list = [ "CH2_alcohol", "CH2_alcohol", "OH_alcohol", "cH_alcohol",]
type = 1
p = [ -0.7347, 0.3257, 0.1465, 1.2068, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alcohol", "OH_alcohol",]
type = 1
p = [ 0.0, 0.82, -0.884, 4.3097, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alkane][CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alcohol", "CH2_alkane", "CH2_alcohol", "OH_alcohol",]
type = 1
p = [ 0.0, 0.82, -0.884, 4.3097, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alkane][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alcohol", "CH2_alkane", "CH2_alkane", "CH2_alkane",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alkane][CH2_alkane][CH2_alcohol]"]
list = [ "CH2_alcohol", "CH2_alkane", "CH2_alkane", "CH2_alcohol",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[OH_alcohol][CH2_alcohol][CH2_alcohol][OH_alcohol]"]
list = [ "OH_alcohol", "CH2_alcohol", "CH2_alcohol", "OH_alcohol",]
type = 6
p = [ 3.3966, -7.8358, 1.8155, 6.6448, -7.0705, -0.0781, 5.4748, 0.2415, 0.0,]
style = "nharmonic"

[torsions."[CH3_alkane][CH2_EOH][OH_EOH][cH_EOH]"]
list = [ "CH3_alkane", "CH2_EOH", "OH_EOH", "cH_EOH",]
type = 1
p = [ -0.7347, 0.3257, 0.1465, 1.2068, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_thiol][SH_thiol][cH_thiol]"]
list = [ "CH2_alkane", "CH2_thiol", "SH_thiol", "cH_thiol",]
type = 1
p = [ 0.0327, 0.3416, -0.3007, 1.4172, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_thiol][SH_thiol]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_thiol", "SH_thiol",]
type = 1
p = [ 0.2651, 2.0545, -1.1238, 3.9753, 0.0,]
style = "opls"

[torsions."[CH3_alkane][CH2_alkane][CH2_thiol][SH_thiol]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_thiol", "SH_thiol",]
type = 1
p = [ 0.2651, 2.0545, -1.1238, 3.9753, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_alkane][CH2_thiol]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH2_thiol",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_thiol][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_alkane", "CH2_thiol",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH3_alkane][CH2_alkane][CH2_alkane][CH2_amine]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_alkane", "CH2_amine",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_amine][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_alkane", "CH2_amine",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_alkane][CH2_amine]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH2_amine",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_amine][NH2_amine][cH_amine]"]
list = [ "CH2_alkane", "CH2_amine", "NH2_amine", "cH_amine",]
type = 1
p = [ 1.2948, -0.2167, -0.6464, 1.0921, 0.0,]
style = "opls"

[torsions."[CH3_alkane][CH2_amine][NH2_amine][cH_amine]"]
list = [ "CH3_alkane", "CH2_amine", "NH2_amine", "cH_amine",]
type = 1
p = [ 1.2948, -0.2167, -0.6464, 1.0921, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_amine][NH2_amine]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_amine", "NH2_amine",]
type = 1
p = [ -0.4586, 0.9541, -0.473, 3.528, 0.0,]
style = "opls"

[torsions."[CH3_alkane][CH2_alkane][CH2_amine][NH2_amine]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_amine", "NH2_amine",]
type = 1
p = [ -0.4586, 0.9541, -0.473, 3.528, 0.0,]
style = "opls"
